// packages/react/components/RadixDropdownMenu.tsx
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { HamburgerMenuIcon } from "@radix-ui/react-icons";
import { DropdownMenuStyle } from "@packages/common/DropdowmnMenu/style";
import type { DropdownMenuProps } from "@packages/common/DropdowmnMenu/type";

const DropdownMenuDemo = ({ items, label }: DropdownMenuProps) => {
  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger asChild>
        <button className={DropdownMenuStyle.Trigger} aria-label={label}>
          <HamburgerMenuIcon />
        </button>
      </DropdownMenu.Trigger>

      <DropdownMenu.Portal>
        <DropdownMenu.Content
          className={DropdownMenuStyle.MenuContent}
          sideOffset={5}
        >
          {items.map((item) => (
            <DropdownMenu.Item
              key={item.label}
              className={DropdownMenuStyle.MenuItem}
              disabled={item.disabled}
            >
              {item.label}
              {item.subItem && (
                <div className={DropdownMenuStyle.MenuSubItem}>
                  {item.subItem}
                </div>
              )}
            </DropdownMenu.Item>
          ))}
        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
  );
};

export default DropdownMenuDemo;

// packages/vue/src/components/RadixDropdownMenu.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { DropdownMenuStyle } from '@packages/common/DropdowmnMenu/style'
import type { DropdownMenuProps } from '@packages/common/DropdowmnMenu/type'
import { ref } from 'vue'
import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuTrigger,
} from 'radix-vue'

defineProps<DropdownMenuProps>()

const toggleState = ref(false)
</script>

<template>
  <DropdownMenuRoot v-model:open="toggleState">
    <DropdownMenuTrigger :class="DropdownMenuStyle.Trigger" :aria-label="label">
      <Icon icon="radix-icons:hamburger-menu" />
    </DropdownMenuTrigger>

    <DropdownMenuPortal>
      <DropdownMenuContent
        :class="DropdownMenuStyle.MenuContent"
        :side-offset="5"
      >
        <DropdownMenuItem
          v-for="item in items"
          :key="item.label"
          :value="item.label"
          :class="DropdownMenuStyle.MenuItem"
          :disabled="item.disabled"
        >
          {{ item.label }}
          <div v-if="item.subItem" :class="DropdownMenuStyle.MenuSubItem">
            {{ item.subItem }}
          </div>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>
